### ISSUE TITLE
Checking Internet connectivity from behind a proxy server

### ISSUE THREAD

**Issue by faheemzunjani** [sindresorhus/is-online-cli#1]
I am working through the proxy server of my college. 

```
$ is-online
```

returns Offline even though Internet works after proxy authentication on the browser.

**Comment by silverwind** [comment]
Assuming macOS, can you post the output of 

```
traceroute google.com -nm 1
dig +short google.com
route -n get default
```

once before and once after authenticating?

**Comment by faheemzunjani** [comment]
El Capitan v10.11.3

Before authenticating: 
![screen shot 2016-07-29 at 10 27 37 pm](https://cloud.githubusercontent.com/assets/13855113/17256634/04e8c56a-55dc-11e6-8f74-8824c751faed.png)
![screen shot 2016-07-29 at 10 28 06 pm](https://cloud.githubusercontent.com/assets/13855113/17256635/05b5489c-55dc-11e6-811d-fcb76c394ed3.png)
![screen shot 2016-07-29 at 10 28 26 pm](https://cloud.githubusercontent.com/assets/13855113/17256637/0765e1b0-55dc-11e6-86b2-8bff2d4845fb.png)

After authenticating:
![screen shot 2016-07-29 at 10 22 45 pm](https://cloud.githubusercontent.com/assets/13855113/17256466/466aa784-55db-11e6-8b12-790e52a85349.png)
![screen shot 2016-07-29 at 10 23 45 pm](https://cloud.githubusercontent.com/assets/13855113/17256469/47a6b9b2-55db-11e6-937d-df8d87a437c3.png)
![screen shot 2016-07-29 at 10 24 14 pm](https://cloud.githubusercontent.com/assets/13855113/17256475/49ecefc0-55db-11e6-9d5f-f839a8a83833.png)

**Comment by silverwind** [comment]
Okay so DNS works regardless of authentication, but we don't know yet who's answering the queries and how that proxy operates exactly. Can you show these before and after authentication:

```
dig . ns @198.41.0.4
curl -v http://wpad/wpad.dat
```

Oh, and sorry about that first command, didn't realize argument order is signifcant as opposed to Linux. But I guess it won't show any meaningful information anyways.

**Comment by silverwind** [comment]
Oh, and

```
ipconfig getpacket en0
```

might be of interest too (shouldn't differ based on authentication)

**Comment by faheemzunjani** [comment]
Before authenticating:
![screen shot 2016-07-30 at 12 08 56 am](https://cloud.githubusercontent.com/assets/13855113/17259599/f1c1f3f4-55e9-11e6-92a1-b4bd8292d0bb.png)
![screen shot 2016-07-30 at 12 09 12 am](https://cloud.githubusercontent.com/assets/13855113/17259601/f380e182-55e9-11e6-900a-73aae7f069fd.png)

After authenticating:
![screen shot 2016-07-30 at 12 01 55 am](https://cloud.githubusercontent.com/assets/13855113/17259481/5047f9ce-55e9-11e6-9c83-c19d3d965314.png)
![screen shot 2016-07-30 at 12 02 36 am](https://cloud.githubusercontent.com/assets/13855113/17259482/517afe36-55e9-11e6-880f-fa1159bb95cf.png)
![screen shot 2016-07-30 at 12 04 31 am](https://cloud.githubusercontent.com/assets/13855113/17259486/58192c4a-55e9-11e6-9a2b-11a74cdb86d8.png)

**Comment by silverwind** [comment]
Hmm, still not sure how this proxy operates, but it looks to not intercept DNS, but also doesn't seem to allow direct connections to the outside. I think we might be able to detect the proxy through HTTP.

@faheemzunjani can you tshow his before and after authentication:

```
curl -v https://icanhazproxy.com
```

And this after authenticating (Replace `Wi-Fi` with the name of your interface):

```
networksetup -getwebproxy "Wi-Fi"
```

**Comment by faheemzunjani** [comment]
Before authenticating:
![screen shot 2016-07-31 at 10 15 13 pm](https://cloud.githubusercontent.com/assets/13855113/17277939/b461d8e2-576c-11e6-836d-6ba6def053a8.png)

After authenticating:
![screen shot 2016-07-31 at 8 33 51 pm](https://cloud.githubusercontent.com/assets/13855113/17277937/ac25049c-576c-11e6-851d-7b5bcb7aff7c.png)
![screen shot 2016-07-31 at 8 47 25 pm](https://cloud.githubusercontent.com/assets/13855113/17277938/ac2767d2-576c-11e6-8e75-533b9fdb18a5.png)

Is it possible that the error is coming because a few ports are blocked by our proxy server like UDP port is blocked here?

**Comment by silverwind** [comment]
> Is it possible that the error is coming because a few ports are blocked by our proxy server like UDP port is blocked here?

It certainly doesn't help that direct outbound DNS (53/upd) seems to be blocked, but that's what our HTTP fallback should ideally solve, but it fails because it has no proxy support yet. 

I haven't worked much with SOCKS proxies (which I assume yours is) yet, but https://github.com/sindresorhus/got#proxies could be used instead of plain HTTP here, I guess: https://github.com/sindresorhus/is-reachable/blob/master/index.js#L39.

**Comment by silverwind** [comment]
Moving this topic to https://github.com/sindresorhus/is-reachable/issues/7.
